### PR TITLE
Add path /config to allow custom api endpoint

### PR DESCRIPTION
**Pull request by steveteuber**
Hey @Mongey.

First, thanks for this really great vault plugin!
In this pull request, I want to add the following paths:

1.  `/config` - Allow custom api endpoint (GitHub Enterprise Server)
2. <s>`/users` - Manage users that allowed to authenticate</s>

Would it be possible to transfer the ownership of this repository to HashiCorp?
In my opinion, this plugin should be part of the [built-in plugin catalog](https://github.com/hashicorp/vault/blob/master/helper/builtinplugins/registry.go#L30)!

What do you think?

### CODE REVIEW

**Comment by Mongey** [comment]
Thanks for the contribution @steveteuber!

> Would it be possible to transfer the ownership of this repository to HashiCorp?
In my opinion, this plugin should be part of the built-in plugin catalog!

I would if they will accept it 😄 

The `/config` path looks good to me.

Can you update the Readme with how to use the `config` path (available options), and also when you might use the `organization` path vs the `user` path.

TBH I will need to refresh my memory on exactly the permissions mapping for this plugin works.
IIRC, currently if you configure the `organizations` path, any action run from a repository in that organization will get the assigned policy. 

Does setting the /users/Mongey mean that my repositories are allowed to get the policies, **or**, that if user Mongey initiates a workflow that authenticates with vault they get a policy ?

I thought the former was already supported 🤔 
https://github.com/Mongey/vault-plugin-auth-github-actions#assign-a-default-policy-to-all-repositories-in-your-organization

It has been 6 months since I have looked though 😓

**Comment by steveteuber** [comment]
Good morning @Mongey.

Thanks, nice to hear that from you! So what I want to do now is to update the readme to answer all your questions 😉
After we use this plugin a few days, I also have some other improvements but this will change the policy mapping path...

I will update this pull request today to add the desired changes.
Then, I will contact HashiCorp that you would accept an ownership transfer.

Thank you and you will hear from me.

**Comment by steveteuber** [comment]
Hey @Mongey.

I have updated the pull request which adds only the /config path.
I'll create a new pull request when I'm finish with the other enhancements.

**Comment by Mongey** [comment]
Thanks @steveteuber! this is great :)

**Pull request merged**
